#line 1 "scanner.cpp"

#line 3 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 116
#define YY_END_OF_BUFFER 117
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[270] =
    {   0,
       95,   95,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  117,  115,  107,  113,  115,  102,  106,   81,
       89,  103,   19,   20,   78,   76,   99,   77,  101,   79,
       96,   98,  100,   85,   62,   86,  105,   97,   97,   97,
       97,   97,   23,  104,   24,   91,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   21,   90,   22,   92,    3,  116,    4,
        6,    5,    8,    7,   11,   12,   14,   13,   16,   15,
      110,  108,  109,  108,  110,  108,  114,  112,  111,   84,

        0,   17,    0,  106,   68,   72,    0,   18,    0,   82,
       65,    0,    0,   63,    0,   64,   95,   80,   66,   95,
       96,   93,   87,   83,   88,   94,   97,    0,   95,   97,
       97,   97,   74,   97,   29,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   45,   97,   47,
       48,   97,   97,   97,   52,   97,   97,   97,   97,   97,
       97,   97,   73,   75,    0,    0,   17,    9,   18,    1,
       69,   95,   67,   95,   71,   70,   97,   97,   97,   28,
       97,   97,   97,   97,   97,   97,   97,   36,   37,   97,
       97,   97,   97,   42,   97,   97,   97,   97,   97,   97,

       51,   97,   97,   97,   56,   97,   97,   97,   10,    2,
       97,   26,   27,   97,   97,   97,   97,   61,   97,   97,
       38,   39,   97,   97,   43,   97,   97,   97,   97,   97,
       53,   97,   97,   97,   58,   97,   25,   97,   31,   32,
       33,   34,   97,   97,   97,   97,   97,   97,   60,   97,
       54,   97,   57,   59,   30,   97,   40,   97,   44,   46,
       49,   97,   55,   97,   41,   97,   35,   50,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   27,   28,
       26,   26,   26,   26,   26,   26,   26,   29,   26,   26,
       26,   26,   26,   30,   26,   26,   26,   26,   26,   26,
       31,   32,   33,   34,   26,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   26,   50,   51,   52,   53,   26,   54,   55,
       56,   26,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[282] =
    {   0,
        0,    0,   55,   56,   57,   58,   63,   64,  322,  321,
      320,  319,  318,  317,   73,   84,  318,  317,  316,  315,
      314,  313,  316,  329,  329,  329,  292,   65,    0,  291,
      290,   68,  329,  329,   59,   82,  329,   85,  293,   75,
       72,  329,  329,   58,  288,   83,  329,    0,   97,  275,
      261,  258,  329,  329,  329,  284,   63,  256,   80,  266,
      104,   79,  259,   86,  268,  267,  253,  250,  264,   95,
      248,   93,  254,  329,  273,  329,  272,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  288,  283,  329,  329,  329,  329,  329,

      113,  286,    0,    0,  329,  329,  128,  281,    0,  267,
      329,  270,  122,  329,  132,  329,  125,  265,  329,  128,
      137,  264,  329,  329,  329,  263,    0,  266,  265,  238,
      235,  228,  329,  242,  102,  244,  239,  226,  241,  228,
      117,  118,  237,  226,  222,  223,  222,    0,  220,    0,
        0,  222,  215,  116,    0,  215,  222,  212,  207,  219,
      209,  221,  329,  329,  253,  248,  329,  329,  329,  329,
      329,  238,  329,  146,  329,  329,  205,  216,  215,    0,
      214,  205,  208,  215,  210,  197,  195,    0,    0,  206,
      206,  205,  208,    0,  196,  205,  192,  203,  201,  192,

        0,  185,  184,  181,    0,  188,  190,  186,  329,  329,
      191,    0,    0,  179,  191,  175,  182,    0,  174,  181,
        0,    0,  174,  177,    0,  186,  170,  181,  172,  136,
        0,  144,  132,  142,    0,  142,    0,  127,    0,    0,
        0,    0,  131,  125,  131,  130,  122,  137,    0,  134,
        0,  123,    0,    0,    0,  113,    0,   94,    0,    0,
        0,  108,    0,  101,    0,   58,    0,    0,  329,  185,
      188,  191,  194,  197,  200,  203,  206,  209,  212,  215,
       89
    } ;

static const flex_int16_t yy_def[282] =
    {   0,
      269,    1,  270,  270,  271,  271,  272,  272,  273,  273,
      274,  274,  275,  275,  276,  276,  277,  277,  277,  277,
      277,  277,  269,  269,  269,  269,  269,  278,  279,  269,
      269,  280,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  281,  281,  281,
      281,  281,  269,  269,  269,  269,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      278,  269,  278,  279,  269,  269,  280,  269,  280,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  281,  269,  281,  281,
      281,  281,  269,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  269,  269,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,    0,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269
    } ;

static const flex_int16_t yy_nxt[390] =
    {   0,
       24,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   48,   64,   48,   65,   66,   67,   68,   69,   70,
       48,   71,   48,   72,   48,   73,   74,   75,   76,   77,
       79,   79,   79,   79,   80,   80,   82,   82,   79,   79,
      102,  110,   84,   84,   92,   93,   92,  108,   94,  122,
      123,  111,   95,   96,   96,   92,   93,   92,  120,   94,
      121,  127,  118,   95,   96,   96,  103,  119,  112,  109,

      113,  112,  268,  113,  114,  125,  126,  116,  115,  134,
      128,  115,  128,  135,  138,  129,  136,  128,  167,  128,
      115,  144,  129,  115,  139,  148,  145,  140,  146,  157,
       96,  149,  150,  158,  160,  161,  151,  169,  120,  267,
      113,   96,  266,  117,  103,  128,  174,  128,  142,  265,
      172,  115,  181,  120,  115,  121,  188,  182,  143,  109,
      190,  189,  200,  115,  174,  264,  115,  201,  191,  263,
      262,  261,  115,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  115,   78,   78,   78,   81,   81,
       81,   83,   83,   83,   85,   85,   85,   87,   87,   87,

       89,   89,   89,   91,   91,   91,   79,   79,   79,  101,
      101,  101,  104,  249,  104,  107,  107,  107,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  172,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  199,  198,  197,  196,
      195,  194,  193,  192,  187,  186,  185,  184,  183,  180,
      179,  178,  177,  129,  172,  176,  175,  173,  117,  171,
      170,  168,  166,  165,  164,  163,  162,  159,  156,  155,

      154,  153,  152,  147,  141,  137,  133,  132,  131,  130,
      124,  117,  106,  105,  100,  269,   99,   99,   98,   98,
       97,   97,   90,   90,   88,   88,   86,   86,   23,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269
    } ;

static const flex_int16_t yy_chk[390] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,    3,    4,    5,    6,    7,    8,
       28,   35,    7,    8,   15,   15,   15,   32,   15,   44,
       44,   35,   15,   15,   15,   16,   16,   16,   41,   16,
       41,  281,   40,   16,   16,   16,   28,   40,   36,   32,

       36,   38,  266,   38,   36,   46,   46,   38,   36,   57,
       49,   38,   49,   57,   59,   49,   57,   61,  101,   61,
       36,   62,   61,   38,   59,   64,   62,   59,   62,   70,
       15,   64,   64,   70,   72,   72,   64,  107,  113,  264,
      113,   16,  262,  117,  101,  115,  120,  115,   61,  258,
      115,  117,  135,  121,  120,  121,  141,  135,   61,  107,
      142,  141,  154,  117,  174,  256,  120,  154,  142,  252,
      250,  248,  174,  247,  246,  245,  244,  243,  238,  236,
      234,  233,  232,  230,  174,  270,  270,  270,  271,  271,
      271,  272,  272,  272,  273,  273,  273,  274,  274,  274,

      275,  275,  275,  276,  276,  276,  277,  277,  277,  278,
      278,  278,  279,  229,  279,  280,  280,  280,  228,  227,
      226,  224,  223,  220,  219,  217,  216,  215,  214,  211,
      208,  207,  206,  204,  203,  202,  200,  199,  198,  197,
      196,  195,  193,  192,  191,  190,  187,  186,  185,  184,
      183,  182,  181,  179,  178,  177,  172,  166,  165,  162,
      161,  160,  159,  158,  157,  156,  153,  152,  149,  147,
      146,  145,  144,  143,  140,  139,  138,  137,  136,  134,
      132,  131,  130,  129,  128,  126,  122,  118,  112,  110,
      108,  102,   95,   94,   77,   75,   73,   71,   69,   68,

       67,   66,   65,   63,   60,   58,   56,   52,   51,   50,
       45,   39,   31,   30,   27,   23,   22,   21,   20,   19,
       18,   17,   14,   13,   12,   11,   10,    9,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pythonTokens.l"










#line 15 "pythonTokens.l"
#pragma warning (disable: 4005)
#include "parser.hpp"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cmath>
#include "classes.hpp"
#include "stack.cpp"
using namespace std;
#line 712 "scanner.cpp"
/* Define token types as constants */
#line 30 "pythonTokens.l"
int numberOfTabs = 0;
int lastNumberOfTabs = 0;
std::string multilineString = "";
#line 718 "scanner.cpp"
/* Regular expressions to match tokens */
#line 720 "scanner.cpp"

#define INITIAL 0
#define S11 1
#define S12 2
#define S13 3
#define S21 4
#define S22 5
#define S23 6
#define tab 7
#define EOF2 8
#define DEDENT1 9
#define LINE 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 143 "pythonTokens.l"


#line 950 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 270 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 329 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 145 "pythonTokens.l"
{
            BEGIN(S11);
            multilineString = "";
}   
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 150 "pythonTokens.l"
{
            BEGIN(S11);
            multilineString = "";
}  
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 155 "pythonTokens.l"
{
            multilineString += yytext;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 159 "pythonTokens.l"
{
            BEGIN(S12);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 163 "pythonTokens.l"
{
            BEGIN(S13);
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 167 "pythonTokens.l"
{
            BEGIN(S11);
            multilineString += "\'";
            multilineString += yytext;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 173 "pythonTokens.l"
{
            BEGIN(INITIAL);
            yylval.astNode = new Multiline_stringNode("multiline_string","multiline_string",multilineString);
            multilineString="";
            return MULTILINE_STRING;
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 180 "pythonTokens.l"
{
            
    		multilineString += "\'";
            multilineString += "\'";
            multilineString += yytext;
            BEGIN(S11);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 189 "pythonTokens.l"
{
            BEGIN(S21);
            multilineString = "";
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 193 "pythonTokens.l"
{
            BEGIN(S21);
            multilineString = "";
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 198 "pythonTokens.l"
{
            multilineString += yytext;
    		
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 203 "pythonTokens.l"
{
            BEGIN(S22);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 207 "pythonTokens.l"
{
            BEGIN(S23);
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 211 "pythonTokens.l"
{
            BEGIN(S21);
            multilineString += "\"";
            multilineString += yytext;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 217 "pythonTokens.l"
{
            BEGIN(INITIAL);
            yylval.astNode = new Multiline_stringNode("multiline_string","multiline_string",multilineString);
            multilineString="";
            return MULTILINE_STRING;
}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 224 "pythonTokens.l"
{
            
            multilineString += "\"";
            multilineString += "\"";
            multilineString += yytext;
            BEGIN(S21);
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 233 "pythonTokens.l"
{

            int curr_len = 0;
            std::string res = "";
            char chars[] = {'t','n','\\','b','f','r','\''};
            int chars_sz = 7;
            char replacement[] = {'\t','\n','\\','\b','\f','\r','\''};
            for (int i=0; i< yyleng; i++)
            {
                if (!(i<yyleng-1 && (yytext[i] == '\\') && (yytext[i+1] == '\n')) )
                {   
                    if(i < yyleng - 1 && yytext[i] == '\\' && (yytext[i + 1] != '\n')){
                        i++;
                        curr_len++;
                        int is_error = 1;
                        for(int j = 0; j < chars_sz; j++){
                            if(yytext[i] == chars[j]){
                                res += " ";
                                res[curr_len - 1] = replacement[j];
                                is_error = 0;
                                break;
                            }
                        }
                        if(is_error){
                            printf("ERROR IN STRING DECLARATION: \\%c\n",yytext[i]);
                        }                        
                    }
                    else{
                        curr_len++;
                        res += " ";
                        res[curr_len - 1] = yytext[i];
                    }
                }
                else{
                    i++;
                }
            }
            yylval.astNode = new String_literalNode("String_literal", "String_literal",res);
            return STRING_LITERAL;
}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 274 "pythonTokens.l"
{

            int curr_len = 0;
            std::string res = "";
            char chars[] = {'t','n','\\','b','f','r','\''};
            int chars_sz = 7;
            char replacement[] = {'\t','\n','\\','\b','\f','\r','\''};
            for (int i=0; i< yyleng; i++)
            {
                if (!(i<yyleng-1 && (yytext[i] == '\\') && (yytext[i+1] == '\n')) )
                {   
                    if(i < yyleng - 1 && yytext[i] == '\\' && (yytext[i + 1] != '\n')){
                        i++;
                        curr_len++;
                        int is_error = 1;
                        for(int j = 0; j < chars_sz; j++){
                            if(yytext[i] == chars[j]){
                                res += " ";
                                res[curr_len - 1] = replacement[j];
                                is_error = 0;
                                break;
                            }
                        }
                        if(is_error){
                            printf("ERROR IN STRING DECLARATION: \\%c\n",yytext[i]);
                        }                        
                    }
                    else{
                        curr_len++;
                        res += " ";
                        res[curr_len - 1] = yytext[i];
                    }
                }
                else{
                    i++;
                }
            }
            yylval.astNode = new String_literalNode("String_literal", "String_literal",res);
            return STRING_LITERAL;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 315 "pythonTokens.l"
{
    return LEFT_PARENTHESIS;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 319 "pythonTokens.l"
{
    return RIGHT_PARENTHESIS;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 323 "pythonTokens.l"
{
    return CURLY_LEFT_BRACKET;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 327 "pythonTokens.l"
{
    return CURLY_RIGHT_BRACKET;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 331 "pythonTokens.l"
{
    return SQUARE_LEFT_BRACKET;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 335 "pythonTokens.l"
{
    return SQUARE_RIGHT_BRACKET;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 339 "pythonTokens.l"
{
    return FALSE;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 343 "pythonTokens.l"
{
    return NONE;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 347 "pythonTokens.l"
{
    return TRUE;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 351 "pythonTokens.l"
{
    return AND;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 355 "pythonTokens.l"
{
    return AS;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 359 "pythonTokens.l"
{
    return ASSERT;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 363 "pythonTokens.l"
{
    return ASYNC;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 367 "pythonTokens.l"
{
    return AWAIT;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 371 "pythonTokens.l"
{
    return BREAK;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 375 "pythonTokens.l"
{
    return CLASS;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 379 "pythonTokens.l"
{
    return CONTINUE;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 383 "pythonTokens.l"
{
    return DEF;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 387 "pythonTokens.l"
{
    return DEL;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 391 "pythonTokens.l"
{
    return ELIF;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 395 "pythonTokens.l"
{
    return ELSE;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 399 "pythonTokens.l"
{
    return EXCEPT;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 403 "pythonTokens.l"
{
    return FINALLY;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 407 "pythonTokens.l"
{
    return FOR;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 411 "pythonTokens.l"
{
    return FROM;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 415 "pythonTokens.l"
{
    return GLOBAL;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 419 "pythonTokens.l"
{
    return IF;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 423 "pythonTokens.l"
{
    return IMPORT;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 427 "pythonTokens.l"
{
    return IN;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 431 "pythonTokens.l"
{
    return IS;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 435 "pythonTokens.l"
{
    return LAMBDA;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 439 "pythonTokens.l"
{
    return NONLOCAL;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 443 "pythonTokens.l"
{
    return NOT;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 447 "pythonTokens.l"
{
    return OR;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 451 "pythonTokens.l"
{
    return PASS;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 455 "pythonTokens.l"
{

    return RAISE;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 460 "pythonTokens.l"
{
    return RETURN;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 464 "pythonTokens.l"
{
    return TRY;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 468 "pythonTokens.l"
{
    return WHILE;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 472 "pythonTokens.l"
{
    return WITH;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 476 "pythonTokens.l"
{
    return YIELD;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 480 "pythonTokens.l"
{
    return MATCH;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 484 "pythonTokens.l"
{
    return CASE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 488 "pythonTokens.l"
{
    return EQUALS;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 492 "pythonTokens.l"
{
    return PLUS_EQUAL;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 496 "pythonTokens.l"
{
    return MINUS_EQUAL;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 500 "pythonTokens.l"
{
    return MULTIPLY_EQUAL;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 504 "pythonTokens.l"
{
    return DIVIDE_EQUAL;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 508 "pythonTokens.l"
{
    return FLOOR_DIVIDE_EQUAL;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 512 "pythonTokens.l"
{
    return MODULO_EQUAL;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 516 "pythonTokens.l"
{
    return EXPONENTIATE_EQUAL;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 520 "pythonTokens.l"
{
    return RIGHT_SHIFT_EQUAL;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 524 "pythonTokens.l"
{
    return LEFT_SHIFT_EQUAL;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 528 "pythonTokens.l"
{
    return BITWISE_AND_EQUAL;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 532 "pythonTokens.l"
{
    return BITWISE_OR_EQUAL;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 536 "pythonTokens.l"
{
    return BITWISE_XOR_EQUAL;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 540 "pythonTokens.l"
{
    return BITWISE_NEGATION_EQUAL;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 544 "pythonTokens.l"
{
    return PLUS;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 548 "pythonTokens.l"
{
    return MINUS;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 552 "pythonTokens.l"
{
    return MULTIPLY;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 556 "pythonTokens.l"
{
    return DIVIDE;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 560 "pythonTokens.l"
{
    return FLOOR_DIVIDE;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 564 "pythonTokens.l"
{
    return MODULO;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 568 "pythonTokens.l"
{
    return EXPONENTIATE;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 572 "pythonTokens.l"
{
    return EQUAL_TO;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 576 "pythonTokens.l"
{
    return NOT_EQUAL_TO;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 580 "pythonTokens.l"
{
    return LESS_THAN;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 584 "pythonTokens.l"
{
    return GREATER_THAN;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 588 "pythonTokens.l"
{
    return LESS_THAN_OR_EQUAL_TO;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 592 "pythonTokens.l"
{
    return GREATER_THAN_OR_EQUAL_TO;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 596 "pythonTokens.l"
{
    return BITWISE_AND;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 600 "pythonTokens.l"
{
    return BITWISE_OR;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 604 "pythonTokens.l"
{
    return BITWISE_XOR;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 608 "pythonTokens.l"
{
    return BITWISE_NEGATION;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 612 "pythonTokens.l"
{
    return LEFT_SHIFT;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 616 "pythonTokens.l"
{
    return RIGHT_SHIFT;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 620 "pythonTokens.l"
{
            yylval.astNode = new Real_numberNode("Real_Number", "Real_Number",std::stof(yytext));
            return REAL_NUMBER;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 625 "pythonTokens.l"
{
            yylval.astNode = new NumberNode("NUMBER", "Integer", atoi(yytext));
            return NUMBER;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 630 "pythonTokens.l"
{
            yylval.astNode = new IdentifierNode("IDENTIFIER", "Identifier", yytext);
            return IDENTIFIER;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 635 "pythonTokens.l"
{
    return COLON;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 639 "pythonTokens.l"
{
    return COMMA;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 643 "pythonTokens.l"
{
    return SEMICOLON;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 647 "pythonTokens.l"
{
    return DOT;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 651 "pythonTokens.l"
{
    return DOUBLE_QUOTATION;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 655 "pythonTokens.l"
{
    return SINGLE_QUOTATION;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 659 "pythonTokens.l"
{
    return BACK_SLASH;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 663 "pythonTokens.l"
{
    return AT_SIGN;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 667 "pythonTokens.l"
{
            yylval.astNode = new CommentNode("Comment", "Comment",yytext);
            return COMMENTS;
}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 673 "pythonTokens.l"
{
            numberOfTabs = 0;
            BEGIN(tab);
            return NEW_LINE;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 679 "pythonTokens.l"
{
            numberOfTabs += yyleng;
}
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 684 "pythonTokens.l"
{
    numberOfTabs = 0;
    BEGIN(tab);
    return NEW_LINE;

}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 691 "pythonTokens.l"
{
    if(isEmpty()){
        push(0);
    }
    unput(yytext[yyleng-1]);
    int states[] = {INDENT,DEDENT,NO_CHANGES};
    int state = -1;
    if (numberOfTabs > lastNumberOfTabs) {
        push(numberOfTabs);
        lastNumberOfTabs = numberOfTabs;
        BEGIN(INITIAL);
        return INDENT;
    } else if (numberOfTabs < lastNumberOfTabs) {
        BEGIN(DEDENT1);
        unput(' ');
        pop();
        lastNumberOfTabs = peek();

        return DEDENT;
    } else {
        BEGIN(INITIAL);
    }
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 715 "pythonTokens.l"
{
    BEGIN(INITIAL);
    return NEW_LINE;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 719 "pythonTokens.l"
{
     if(isEmpty()){
        push(0);
    }
    if (numberOfTabs < lastNumberOfTabs )
    {  
        unput(' ');
        pop();
        lastNumberOfTabs = peek();
        return DEDENT;
    }
    else if(numberOfTabs > lastNumberOfTabs)
    {
        std::cerr << "lex error: " << "Dedent error" << std::endl;

    }
    else
    {
        lastNumberOfTabs = numberOfTabs;
        unput(' ');
        BEGIN(LINE);
        }
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 743 "pythonTokens.l"
{
            //printf("WHAIT SPACE\n");
            //return WHAIT_SPACE;
            
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S11):
case YY_STATE_EOF(S12):
case YY_STATE_EOF(S13):
case YY_STATE_EOF(S21):
case YY_STATE_EOF(S22):
case YY_STATE_EOF(S23):
case YY_STATE_EOF(tab):
case YY_STATE_EOF(EOF2):
case YY_STATE_EOF(DEDENT1):
case YY_STATE_EOF(LINE):
#line 748 "pythonTokens.l"
{
    BEGIN(EOF2);
    unput(' ');
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 752 "pythonTokens.l"
{
    if(isEmpty()){
        push(0);
    }
    pop();
    if(!isEmpty())
    {
        unput(' ');
        return DEDENT;
    }
    else
        return ENDMARKER;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 765 "pythonTokens.l"
{
            return UNKNOWN_SYMBOL;
    }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 770 "pythonTokens.l"
ECHO;
	YY_BREAK
#line 2004 "scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 270 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 270 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 269);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 770 "pythonTokens.l"


